version: "3.9"
services:
  pingvin:
    container_name: Pingvin-Share
    image: laichaoyi/pingvin-share
    healthcheck:
     test: curl -f http://localhost:3000/ || exit 1
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - 6090:3000
    volumes:
      - /volume1/docker/pingvin:/opt/app/backend/data:rw
      - /volume1/docker/pingvin/public:/opt/app/frontend/public/img:rw
